In [18]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [19]:
a = frozenset([1,2,3])
b = frozenset(list(a) + [6])
print(a,b)
print(1 in a)

frozenset({1, 2, 3}) frozenset({1, 2, 3, 6})
True


In [1]:
import vehicles
x = vehicles.JsonVehicleProvider("../subgame/python/solutions.json")
print(x.next())

Vehicle(risk=5.78, in_platoon=False, compromises=frozenset(), known_compromises=frozenset(), defender_choices=frozenset({Vulnerability(id=5, attackerCost=1, defenderCost=1, attackerProb=0.9, defenderProb=0.85, severity=3), Vulnerability(id=4, attackerCost=2, defenderCost=5, attackerProb=0.69, defenderProb=0.85, severity=3), Vulnerability(id=2, attackerCost=4, defenderCost=4, attackerProb=0.2, defenderProb=0.97, severity=5)}), attacker_choices=frozenset({Vulnerability(id=3, attackerCost=5, defenderCost=1, attackerProb=0.15, defenderProb=0.85, severity=4), Vulnerability(id=5, attackerCost=1, defenderCost=1, attackerProb=0.9, defenderProb=0.85, severity=3), Vulnerability(id=0, attackerCost=4, defenderCost=3, attackerProb=0.54, defenderProb=0.85, severity=2)}))
Vehicle(risk=5.78, in_platoon=False, compromises=frozenset(), known_compromises=frozenset(), defender_choices=frozenset({Vulnerability(id=5, attackerCost=1, defenderCost=1, attackerProb=0.9, defenderProb=0.85, severity=3), Vulnerabi

In [6]:
class Animal:
    def __init__(self, wag) -> None:
        self.wag = wag
        print(wag)

    def bark(self):
        print("hi")
        return 3

class Bean:
    def __init__(self, wag) -> None:
        self.wag = wag + 10
        print(wag + 10)

    def bark(self): 
        print("zee" + str(self.wag))
        return 4

class zed(Bean, Animal):
    pass

zed(5).bark()

15
zee15


4

In [4]:
a = [1,2,3,4,5]
i = 4
print(a[i])
print(a[:i] + [99] + a[i+1:])

5
[1, 2, 3, 4, 99]


In [2]:
set([1,2,3]).intersection(set([3,4,5]))

{3}

In [1]:
%timeit len([1 for x in range(10000000)])

356 ms ± 22.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [2]:
%timeit sum(1 for x in range(10000000))

464 ms ± 2.25 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [1]:
import numpy as np
np.diff(list(range(100)))

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [2]:
import random
random.sample([1,2,3,4,5], 0)

[]

In [16]:
import torch
a = torch.ones((3,3,3)).flatten(start_dim=1)
b = (torch.ones((3,4,4)) * 2).flatten(start_dim=1)
print(a)
print(b)
c = torch.cat((a,b), dim=1)
print(c)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2.]])


In [27]:
a = [("a","b"),("a","b"),("a","b")]
a = [("a","b")]

print(a)
a = tuple(zip(*a))
print(a)
print()

a = [("a","b")]

print(a)
a = list(zip(*a))
print(a)
print()

a = [("a","b")]
print(a)
a = tuple(map(list, zip(*a)))
print(a)


[('a', 'b')]
(('a',), ('b',))

[('a', 'b')]
[('a',), ('b',)]

[('a', 'b')]
(['a'], ['b'])


In [1]:
def asd(a, b):
    print("got",a,"and",b)
asd(*(23,545))

got 23 and 545


In [3]:
def dsa(a,b,c,d):
    print(f"a={a} b={b} c={c} d={d}")
dsa(*(321,55),*(87,99))

a=321 b=55 c=87 d=99


In [5]:
from typing import List


a: List[int] = []
a=False

In [7]:
import torch

a = torch.zeros((5,3))
b = torch.stack([a,a,a])
print(a.shape)
print(b.shape)

torch.Size([5, 3])
torch.Size([3, 5, 3])


In [9]:
list(zip(*[(1,2) for _ in range(5)]))

[(1, 1, 1, 1, 1), (2, 2, 2, 2, 2)]

In [16]:
tuple(v for v in range(5))

(0, 1, 2, 3, 4)

In [19]:
from game import StateTensors
StateTensors(torch.zeros((3,)) for _ in range(2))

TypeError: __init__() missing 1 required positional argument: 'vehicles'

In [24]:
a=StateTensors(torch.zeros(4), torch.zeros(5))
b=[a,a,a,a,a,a,a,a]
list(zip(*[(v.vehicles, v.vulnerabilities) for v in b]))

[(tensor([0., 0., 0., 0., 0.]),
  tensor([0., 0., 0., 0., 0.]),
  tensor([0., 0., 0., 0., 0.]),
  tensor([0., 0., 0., 0., 0.]),
  tensor([0., 0., 0., 0., 0.]),
  tensor([0., 0., 0., 0., 0.]),
  tensor([0., 0., 0., 0., 0.]),
  tensor([0., 0., 0., 0., 0.])),
 (tensor([0., 0., 0., 0.]),
  tensor([0., 0., 0., 0.]),
  tensor([0., 0., 0., 0.]),
  tensor([0., 0., 0., 0.]),
  tensor([0., 0., 0., 0.]),
  tensor([0., 0., 0., 0.]),
  tensor([0., 0., 0., 0.]),
  tensor([0., 0., 0., 0.]))]

In [31]:
import torch
torch.as_tensor(list(x for x in range(5)))

tensor([0, 1, 2, 3, 4])

In [35]:
a = torch.as_tensor([1,2,3,4])
r = torch.as_tensor([3,4,5,6])
b = [False,True,True,False]
a[b] += -1 * r[b]
print(a)

tensor([ 1, -2, -2,  4])


In [41]:
a = torch.as_tensor(list([i for i in range(10)]))
b = frozenset([3,5,7])
a[list(b)] = -1
print(a)


tensor([ 0,  1,  2, -1,  4, -1,  6, -1,  8,  9])


In [42]:
a = [1,2,3,4,5]
3 in a

True

In [43]:
a = (4,5,6)
print(replace(a, 2, 5))

NameError: name 'replace' is not defined

In [47]:
a = torch.randn((2,30))
print(a)
a = a.heaviside(torch.tensor(1.))
print(a)


tensor([[-2.0922,  0.1683,  0.5359,  0.2814, -0.2734, -1.2071, -0.1854, -2.1647,
          0.5430, -0.0662, -0.2084, -1.1123,  1.0920,  0.8870,  1.2893,  0.0816,
         -0.5979, -0.4983,  0.4677, -1.1966, -0.2003, -1.4302,  1.9543,  0.2031,
          0.3300, -0.5353,  0.4217, -0.6558, -0.5075,  0.0821],
        [ 2.3974, -0.3981,  1.1553,  0.2325, -0.6020,  1.2619, -0.3430,  1.5097,
         -0.5900,  1.2804,  0.3886, -1.6676, -2.2727,  0.4238,  0.6324, -0.9350,
          0.3174,  0.4497,  0.4562,  0.9700,  0.4833, -0.4236,  0.2571,  0.0699,
         -0.4167,  0.1543, -1.1786,  1.8663, -0.8918, -1.2374]])
tensor([[0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0.,
         1., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 1.],
        [1., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1.,
         1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 0., 0.]])


In [50]:
torch.rand(4).unsqueeze(dim=0)

tensor([[0.2183, 0.8166, 0.4535, 0.7398]])

In [51]:
a = torch.rand(4)
print(a)
print(a.argmax())


tensor([0.8590, 0.9213, 0.7008, 0.5416])
tensor(1)


In [62]:
a = torch.as_tensor([0,0,0,1,1,0,0,0,1])
print(a)
print(a.nonzero())
print(a.nonzero().squeeze())
print(a.nonzero().reshape((1,-1)))

tensor([0, 0, 0, 1, 1, 0, 0, 0, 1])
tensor([[3],
        [4],
        [8]])
tensor([3, 4, 8])
tensor([[3, 4, 8]])


In [63]:
a = torch.as_tensor([
    [0,0,1,1,1,0,0],
    [1,1,1,0,0,0,0],
])
print(a)
print(a[0].nonzero().squeeze())
print(a[0].nonzero().reshape((1,-1)))

tensor([[0, 0, 1, 1, 1, 0, 0],
        [1, 1, 1, 0, 0, 0, 0]])
tensor([2, 3, 4])
tensor([[2, 3, 4]])
