In [5]:
import torch
import torch.nn.functional as F
import torch.nn as nn

batch_size=3
max_vehicles = 10
max_vulns = 7
vuln_width = 4
vuln_conv = nn.Conv2d(
    in_channels=vuln_width,
    out_channels=5,
    stride=2,
    kernel_size=2
)
x = torch.ones((batch_size, max_vehicles, max_vulns, vuln_width))
print(x.shape, "raw", "NHWC")
x = x.permute((0,3,1,2))
print(x.shape, "permuted", "NCHW")
x = vuln_conv(x)
print(x.shape, "convd")
norm = nn.LazyBatchNorm2d()
x = norm(x)
print(x.shape, "norm")
x = F.relu(x)
print(x.shape, "relu")

torch.Size([3, 10, 7, 4]) raw NHWC
torch.Size([3, 4, 10, 7]) permuted NCHW
torch.Size([3, 5, 5, 3]) convd
torch.Size([3, 5, 5, 3]) norm
torch.Size([3, 5, 5, 3]) relu


c:\Users\TeamD\.conda\envs\subgame\lib\site-packages\torch\nn\modules\lazy.py:178: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [ ]:
import vehicles
import game
import agents
import evaluation
import torch

In [ ]:
engine = evaluation.Evaluator(
    # attacker=agents.PassiveAgent(),
    attacker=agents.BasicAttackerAgent(1),
    defender=agents.BasicDefenderAgent(monitor_limit=1),
    vehicles=vehicles.JsonVehicleProvider("../subgame/python/solutions.json"),
    game_config=game.GameConfig(
        max_vehicles=30,
        cycle_every=3,
        cycle_num=5,
        cycle_allow_platoon=False
    ),
    num_rounds=1000
)
engine.reset()

In [ ]:
engine.game.state.vehicles[0].vulnerabilities[0].as_tensor()

tensor([0.9400, 1.0000, 0.0000, 0.0000])

In [ ]:
batch_size = 3
vulns_quants = []
vehicle_quants = []
for _ in range(batch_size):
    vulns_quant, vehicle_quant = engine.game.state.as_tensors(engine.game_config.max_vehicles, engine.vehicles.max_vulns)
    vulns_quants.append(vulns_quant)
    vehicle_quants.append(vehicle_quant)

vulns_quant = torch.stack(vulns_quants)
vehicle_quant = torch.stack(vehicle_quants)
print(vulns_quant.shape)
print(vehicle_quant.shape)
del vulns_quants
del vehicle_quants

torch.Size([3, 30, 7, 4])
torch.Size([3, 30, 2])


In [ ]:
import reinforcement_learning
agent = reinforcement_learning.RLDefenderAgent(engine.game)
y = agent.policy_net(vulns_quant, vehicle_quant)
print(y[0].shape, y[1].shape)

torch.Size([3, 8, 13, 2]) torch.Size([3, 4, 29])
torch.Size([972])
torch.Size([30]) torch.Size([30])


c:\Users\TeamD\.conda\envs\subgame\lib\site-packages\torch\nn\modules\lazy.py:178: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [ ]:
from torchsummary import summary
summary(agent.policy_net)

Layer (type:depth-idx)                   Param #
├─Conv2d: 1-1                            808
├─BatchNorm2d: 1-2                       16
├─Conv1d: 1-3                            20
├─BatchNorm1d: 1-4                       8
├─Linear: 1-5                            2,530
├─Linear: 1-6                            2,530
Total params: 5,912
Trainable params: 5,912
Non-trainable params: 0


Layer (type:depth-idx)                   Param #
├─Conv2d: 1-1                            808
├─BatchNorm2d: 1-2                       16
├─Conv1d: 1-3                            20
├─BatchNorm1d: 1-4                       8
├─Linear: 1-5                            2,530
├─Linear: 1-6                            2,530
Total params: 5,912
Trainable params: 5,912
Non-trainable params: 0

In [20]:
import torch
x = torch.randn(30)
print(x)
x = x.heaviside(torch.tensor(1.))
print(x)
x = ((x == 1).nonzero().squeeze())
print(x)
print(frozenset(x.numpy()))

tensor([-0.0086,  0.0122, -0.5581,  0.5493,  0.2074,  1.0648,  0.9339, -0.7565,
         0.6404, -0.0040,  1.1001, -0.0658, -0.9233, -0.0207,  1.8461,  1.5032,
         0.9084,  0.4523,  0.9821, -1.6651, -0.6420, -0.8580, -0.9656, -1.0564,
         1.8804,  0.0318,  0.4744, -0.2340,  1.1124, -0.7272])
tensor([0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1.,
        1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0.])
tensor([ 1,  3,  4,  5,  6,  8, 10, 14, 15, 16, 17, 18, 24, 25, 26, 28])
frozenset({1, 3, 4, 5, 6, 8, 10, 14, 15, 16, 17, 18, 24, 25, 26, 28})
